# Naive Bayes Classification

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("E:/Dataset/play_tennis.csv")

In [3]:
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

## Problems

In [6]:
# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or not play ??

In [8]:
# Solution

# P(Yes|Sunny, Hot, High, Weak) = P(Sunny|Yes) * P(Hot|Yes) * P(High|Yes) * P(Weak|Yes)
# P(No|Sunny, Hot, High, Weak) = P(Sunny|No) * P(Hot|No) * P(High|No) * P(Weak|No)

# Compare and decide using the Maximun a Posteriori (MAP) Rule

In [36]:
# Problem 2

# Outlook=Overcast, Temp=Cold, Humidity=Normal, Wind=Weak
# Play or not play ??

In [35]:
# Solution

# P(Yes|Overcast, Cool, Normal, Weak) = P(Overcast|Yes) * P(Cool|Yes) * P(Normal|Yes) * P(Weak|Yes)
# P(No|Overcast, Cool, Normal, Weak) = P(Overcast|No) * P(Cool|No) * P(Normal|No) * P(Weak|No)

# Compare and decide using the Maximun a Posteriori (MAP) Rule

### How **Naive Bayes' Theorem** works

In [11]:
# Training

# Create Lookup table, and store values in a Data Structure like, dictionary

# Use this Lookup table and predict values

### Creating our own lookup table

#### For output column

In [13]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [14]:
P_Yes = 9/14
P_No = 5/14

In [15]:
print(f"Probability of Yes:", P_Yes)
print(f"Probability of No:", P_No)

Probability of Yes: 0.6428571428571429
Probability of No: 0.35714285714285715

#### For Outlook feature

In [17]:
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [20]:
P_Overcast_Yes = 4/9
P_Rain_Yes = 3/9
P_Sunny_Yes = 2/9

P_Overcast_No = 0
P_Rain_No = 2/5
P_Sunny_No = 3/5

#### For Temperature

In [19]:
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [21]:
P_Cool_Yes = 3/9
P_Hot_Yes = 2/9
P_Mild_Yes = 4/9

P_Cool_No = 1/5
P_Hot_No = 2/5
P_Mild_No = 2/5

#### For Wind

In [22]:
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [23]:
P_Strong_Yes = 3/9
P_Weak_Yes = 6/9

P_Strong_No = 3/5
P_Weak_No = 2/5

#### For Humidity

In [24]:
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [25]:
P_High_Yes = 3/9
P_Normal_Yes = 6/9

P_High_No = 4/5
P_Normal_No = 1/5

### Solution part

In [31]:
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak

Prob_Yes = (P_Sunny_Yes * P_Hot_Yes * P_High_Yes * P_Weak_Yes) * P_Yes
print(f"Probability of yes =", Prob_Yes)

Prob_No = (P_Sunny_No * P_Hot_No * P_High_No * P_Weak_No) * P_No
print(f"Probability of No =", Prob_No)

Probability of yes = 0.007054673721340387
Probability of No = 0.02742857142857143

#### That means for problem-1 player will not play

In [38]:
# Outlook=Overcast, Temp=Cool, Humidity=Normal, Wind=Weak

Prob_Yes2 = (P_Overcast_Yes * P_Cool_Yes * P_Normal_Yes * P_Weak_Yes) * P_Yes
print(f"Probability of yes =", Prob_Yes2)

Prob_No2 = (P_Overcast_No * P_Cool_No * P_Normal_No * P_Weak_No) * P_No
print(f"Probability of No =", Prob_No2)

Probability of yes = 0.042328042328042326
Probability of No = 0.0

#### That means for problem-2 players will play