# Classification metrics for **more than two classes**

### Loading data

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('E:/Dataset/Iris.csv')

In [3]:
df.sample(3)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
37,38,4.9,3.1,1.5,0.1,Iris-setosa
132,133,6.4,2.8,5.6,2.2,Iris-virginica
36,37,5.5,3.5,1.3,0.2,Iris-setosa

In [4]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

### Encoding categorical data

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
encoder = LabelEncoder()

In [10]:
encoder.fit(y)

LabelEncoder()

In [11]:
encoder.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [12]:
y_encoded = encoder.transform(y)

In [13]:
y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Splitting data

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=17)

### Training model

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [18]:
log_reg = LogisticRegression()
dec_tree = DecisionTreeClassifier()

In [19]:
log_reg.fit(x_train, y_train)
dec_tree.fit(x_train, y_train)

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [20]:
y_pred1 = log_reg.predict(x_test)
y_pred2 = dec_tree.predict(x_test)

### Calculating metrices

In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [30]:
print(f"Accuracy(Logistic Regression): {accuracy_score(y_test, y_pred1)}")
print(f"Accuracy(Decision Tree): {accuracy_score(y_test, y_pred2)}")

Accuracy(Logistic Regression): 1.0
Accuracy(Decision Tree): 1.0

In [31]:
print(f"Confusion Matrics (Logistic Regression):\n {confusion_matrix(y_test, y_pred1)}")
print(f"\nConfusion Matrix(Decision Tree):\n {confusion_matrix(y_test, y_pred2)}")

Confusion Matrics (Logistic Regression):
 [[ 7  0  0]
 [ 0 11  0]
 [ 0  0 12]]

Confusion Matrix(Decision Tree):
 [[ 7  0  0]
 [ 0 11  0]
 [ 0  0 12]]

In [29]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [34]:
print(f"Precision(Logistic Regression): {precision_score(y_test, y_pred1, average=None)}")
print(f"Precision(Decision Tree): {precision_score(y_test, y_pred2, average=None)}")

print(f"\nRecall(Logistic Regression): {recall_score(y_test, y_pred1, average=None)}")
print(f"Recall(Decision Tree): {recall_score(y_test, y_pred2, average=None)}")

print(f"\nF1 Score(Logistic Regression): {f1_score(y_test, y_pred1, average=None)}")
print(f"F1 Score(Decision Tree): {f1_score(y_test, y_pred2, average=None)}")

Precision(Logistic Regression): [1. 1. 1.]
Precision(Decision Tree): [1. 1. 1.]

Recall(Logistic Regression): [1. 1. 1.]
Recall(Decision Tree): [1. 1. 1.]

F1 Score(Logistic Regression): [1. 1. 1.]
F1 Score(Decision Tree): [1. 1. 1.]

In [35]:
from sklearn.metrics import classification_report

In [41]:
print(f"Classification Report for Logistic Regression:\n\n {classification_report(y_test, y_pred1)}")

Classification Report for Logistic Regression:

               precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

## On mnist dataset (digit classification)

In [5]:
df1 = pd.read_csv('E:/Dataset/digit_recognition.csv')

In [6]:
df1.sample(2)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
37058,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29698,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
x1 = df1.iloc[:, 1:]
y1 = df1.iloc[:, 0]

In [16]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(x1, y1, test_size=0.2, random_state=17)

#### Model - 2

In [21]:
log_reg1 = LogisticRegression()
dec_tree1 = DecisionTreeClassifier()

In [22]:
log_reg1.fit(x_train1, y_train1)
dec_tree1.fit(x_train1, y_train1)

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [23]:
y_pred3 = log_reg1.predict(x_test1)
y_pred4 = dec_tree1.predict(x_test1)

In [27]:
print(f"Accuracy(Logistic Regression): {accuracy_score(y_test1, y_pred3)}")
print(f"Accuracy(Decision Tree): {accuracy_score(y_test1, y_pred4)}")

Accuracy(Logistic Regression): 0.9161904761904762
Accuracy(Decision Tree): 0.8496428571428571

In [28]:
print(f"Confusion Matrics (Logistic Regression):\n {confusion_matrix(y_test1, y_pred3)}")
print(f"\nConfusion Matrix(Decision Tree):\n {confusion_matrix(y_test1, y_pred4)}")

Confusion Matrics (Logistic Regression):
 [[831   0   4   3   2   6   7   3   4   2]
 [  0 891   5   3   1   5   1   1  11   3]
 [  6  11 759  19   6   3  13  16  22   3]
 [  5   2  18 789   0  32   2  11  15   9]
 [  2   3   4   3 708   2   9   2   6  22]
 [ 13   1   4  31   9 647   6   2  24  11]
 [  4   3   7   0   8  14 750   0   4   1]
 [  2   2   9   6   4   2   2 849   6  31]
 [  3  16  10  24   4  21   8   4 721  17]
 [  1   3   2  14  21   9   0  28   6 751]]

Confusion Matrix(Decision Tree):
 [[791   3   8   3  10  10  13   3  12   9]
 [  0 848  15  16   6  12   1   2  13   8]
 [ 10  19 698  30  20   9  13  21  28  10]
 [ 12  13  25 728  10  34   7  14  28  12]
 [  4   6  11   6 637   6  20   9  24  38]
 [  8   4  13  44   9 586  20  12  36  16]
 [  9   9  10   5  19  23 699   1  12   4]
 [  8   6  19  10   8   6   1 819   8  28]
 [ 13  16  33  41  18  29  14  12 627  25]
 [  7   5   4  22  27  15   4  29  18 704]]

In [45]:
print(f"Precision(Logistic Regression):\n {precision_score(y_test1, y_pred3, average=None)}")
print(f"\nPrecision(Decision Tree):\n {precision_score(y_test1, y_pred4, average=None)}")

print(f"\n\nRecall(Logistic Regression):\n {recall_score(y_test1, y_pred3, average=None)}")
print(f"\nRecall(Decision Tree):\n {recall_score(y_test1, y_pred4, average=None)}")

print(f"\n\nF1 Score(Logistic Regression):\n {f1_score(y_test1, y_pred3, average=None)}")
print(f"\nF1 Score(Decision Tree):\n {f1_score(y_test1, y_pred4, average=None)}")

Precision(Logistic Regression):
 [0.95847751 0.95600858 0.92335766 0.88452915 0.92791612 0.8731444
 0.93984962 0.9268559  0.88034188 0.88352941]

Precision(Decision Tree):
 [0.91763341 0.91280947 0.83492823 0.80441989 0.83376963 0.80273973
 0.88257576 0.88828633 0.77791563 0.82435597]


Recall(Logistic Regression):
 [0.96403712 0.96742671 0.88461538 0.89354473 0.9303548  0.86497326
 0.94816688 0.92990142 0.87077295 0.8994012 ]

Recall(Decision Tree):
 [0.91763341 0.92073833 0.81351981 0.82446206 0.8370565  0.78342246
 0.88369153 0.89704272 0.75724638 0.84311377]


F1 Score(Logistic Regression):
 [0.96124928 0.96168376 0.90357143 0.88901408 0.92913386 0.86903962
 0.94398993 0.92837616 0.87553127 0.89139466]

F1 Score(Decision Tree):
 [0.91763341 0.91675676 0.82408501 0.81431767 0.83540984 0.79296346
 0.88313329 0.89264305 0.76744186 0.83362937]

In [47]:
print("Classification Report (Logistic Regression):\n")
print(classification_report(y_test1, y_pred3))

Classification Report (Logistic Regression):

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       862
           1       0.96      0.97      0.96       921
           2       0.92      0.88      0.90       858
           3       0.88      0.89      0.89       883
           4       0.93      0.93      0.93       761
           5       0.87      0.86      0.87       748
           6       0.94      0.95      0.94       791
           7       0.93      0.93      0.93       913
           8       0.88      0.87      0.88       828
           9       0.88      0.90      0.89       835

    accuracy                           0.92      8400
   macro avg       0.92      0.92      0.92      8400
weighted avg       0.92      0.92      0.92      8400

In [49]:
print("Classification Report (Decision Tree):\n")
print(classification_report(y_test1, y_pred4))

Classification Report (Decision Tree):

              precision    recall  f1-score   support

           0       0.92      0.92      0.92       862
           1       0.91      0.92      0.92       921
           2       0.83      0.81      0.82       858
           3       0.80      0.82      0.81       883
           4       0.83      0.84      0.84       761
           5       0.80      0.78      0.79       748
           6       0.88      0.88      0.88       791
           7       0.89      0.90      0.89       913
           8       0.78      0.76      0.77       828
           9       0.82      0.84      0.83       835

    accuracy                           0.85      8400
   macro avg       0.85      0.85      0.85      8400
weighted avg       0.85      0.85      0.85      8400