# How to Gather data from all different sources

In [2]:
import pandas as pd

## Working with JSON

In [9]:
df = pd.read_json("E:/Dataset/recipe_json/train.json")

In [10]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [11]:
print("E:\\Dataset\\recipe_json\\train.json")
print("E:/Dataset/recipe_json/train.json")
print(r"E:\Dataset\recipe_json\train.json")

E:\Dataset\recipe_json\train.json
E:/Dataset/recipe_json/train.json
E:\Dataset\recipe_json\train.json

## Working with SQL

In [12]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in e:\anaconda\anaconda2\lib\site-packages (2.2.9)

In [13]:
import mysql.connector

In [7]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world')

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (10061 No connection could be made because the target machine actively refused it)

In [ ]:
pd.read_sql_query("SELECT * FROM city", conn)

In [ ]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'", conn)

In [ ]:
pd.read_sql_query("SELECT * FROM country", conn)

In [ ]:
pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy > 60", conn)

In [ ]:
pd.read_sql_query("SELECT * FROM countrylanguage", conn)

In [ ]:
pd.read_sql_query("SELECT * FROM countrylanguage WHERE IsOfficial like 'T'", conn)

In [ ]:
df = pd.read_sql_query("SELECT * FROM countrylanguage", conn)

In [ ]:
print(df)

## Working with API

In [4]:
import pandas as pd
import requests

In [5]:
# API return response only
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=7cd40b45311cdcda7d0520f688bd6d02&language=en-US&page=1")

In [6]:
# Convert data from response into json formate, and get only results
res = response.json()['results']

In [7]:
# Finding only required columns
df = pd.DataFrame(res)[['id', 'original_title', 'popularity', 'release_date', 'title', 'vote_average', 'vote_count']]

In [8]:
df

,id,original_title,popularity,release_date,title,vote_average,vote_count
0,278,The Shawshank Redemption,53.1676,1994-09-23,The Shawshank Redemption,8.718,30056
1,238,The Godfather,36.3000,1972-03-14,The Godfather,8.700,22701
2,240,The Godfather Part II,26.6297,1974-12-20,The Godfather Part II,8.572,13749
3,424,Schindler's List,23.9618,1993-12-15,Schindler's List,8.567,17277
4,389,12 Angry Men,18.2003,1957-04-10,12 Angry Men,8.558,9869
5,1181678,¿Quieres ser mi hijo?,8.8111,2023-09-21,¿Quieres ser mi hijo?,8.600,307
6,129,千と千尋の神隠し,32.4870,2001-07-20,Spirited Away,8.534,18137
7,155,The Dark Knight,30.2136,2008-07-16,The Dark Knight,8.528,35435
8,19404,दिलवाले दुल्हनिया ले जायेंगे,13.9711,1995-10-20,Dilwale Dulhania Le Jayenge,8.515,4572
9,497,The Green Mile,26.1986,1999-12-10,The Green Mile,8.504,19036
10,122,The Lord of the Rings: The Return of the King,29.2595,2003-12-17,The Lord of the Rings: The Return of the King,8.496,26281
11,496243,기생충,31.3445,2019-05-30,Parasite,8.493,20373
12,680,Pulp Fiction,28.3074,1994-09-10,Pulp Fiction,8.486,29943
13,372058,君の名は。,27.6691,2016-08-26,Your Name.,8.477,12406
14,157336,Interstellar,57.9049,2014-11-05,Interstellar,8.469,39296
15,429,"Il buono, il brutto, il cattivo",17.8460,1966-12-23,"The Good, the Bad and the Ugly",8.468,9527
16,13,Forrest Gump,22.9393,1994-06-23,Forrest Gump,8.463,29477
17,769,GoodFellas,23.3662,1990-09-12,GoodFellas,8.452,14179
18,346,七人の侍,16.6606,1954-04-26,Seven Samurai,8.451,4168
19,12477,火垂るの墓,0.0132,1988-04-16,Grave of the Fireflies,8.444,6440

In [9]:
dfs = pd.DataFrame()

In [10]:
dfs

Empty DataFrame
Columns: []
Index: []

In [20]:
for i in range(0, 1):
    url = "https://api.themoviedb.org/3/movie/top_rated?api_key=7cd40b45311cdcda7d0520f688bd6d02&language=en-US&page={}".format(i+1)
    headers = {"Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3Y2Q0MGI0NTMxMWNkY2RhN2QwNTIwZjY4OGJkNmQwMiIsIm5iZiI6MTc3NTQwMjg3Ni40MDcsInN1YiI6IjY5ZDI3ZjdjZjZlOGE1MWEzYWQwNDVhZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.xG5Fl-KYhOiad_T7twZELnAPf-k9IfPYK-_pbVRwFwk"}
    resp = requests.get(url, headers=headers)
    rslt = resp.json()['results']
    temp_df = pd.DataFrame(rslt)[['id', 'original_title', 'popularity', 'release_date', 'title', 'vote_average', 'vote_count']]
    dfs = pd.concat([dfs, temp_df], ignore_index=True)
    resp.close()

In [21]:
dfs

,id,original_title,popularity,release_date,title,vote_average,vote_count
0,278,The Shawshank Redemption,53.1676,1994-09-23,The Shawshank Redemption,8.718,30056
1,238,The Godfather,36.3000,1972-03-14,The Godfather,8.700,22701
2,240,The Godfather Part II,26.6297,1974-12-20,The Godfather Part II,8.572,13749
3,424,Schindler's List,23.9618,1993-12-15,Schindler's List,8.567,17277
4,389,12 Angry Men,18.2003,1957-04-10,12 Angry Men,8.558,9869
...,...,...,...,...,...,...,...
95,429,"Il buono, il brutto, il cattivo",17.8460,1966-12-23,"The Good, the Bad and the Ugly",8.468,9527
96,13,Forrest Gump,22.9393,1994-06-23,Forrest Gump,8.463,29477
97,769,GoodFellas,23.3662,1990-09-12,GoodFellas,8.452,14179
98,346,七人の侍,16.6606,1954-04-26,Seven Samurai,8.451,4168
99,12477,火垂るの墓,0.0132,1988-04-16,Grave of the Fireflies,8.444,6440

In [22]:
dfs.to_csv('movies.csv')

## Working with Web Scrabing

In [36]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [40]:
url = "https://www.ambitionbox.com/list-of-companies?page=1"
requests.get(url)

In [46]:
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
webpage = requests.get(url, headers=headers).text

In [54]:
soup = BeautifulSoup(webpage, 'lxml')

In [66]:
#soup.prettify()

### Basics to understand how to extract data from a webpage

In [60]:
len(soup.find_all('h2'))

24

In [63]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
ICICI Bank
HCLTech
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [67]:
com = soup.find_all('h2')
for i in range(1,21):
    print(com[i].text.strip())

TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
ICICI Bank
HCLTech
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM

In [82]:
soup.find_all('div', class_='rating_text')[0].find('div').text.strip()

'3.3'

### Now we will go through

#### Work for a single page

In [83]:
companies = soup.find_all('div', class_='companyCardWrapper')

In [85]:
len(companies)

20

In [145]:
name = []
rating = []
reviews = []
c_type = []
loc = []
salary = []

i = 0

for company in companies:
    name.append(company.find('h2').text.strip())
    rating.append(company.find('div', class_='rating_text').text.strip())
    rat_count = company.find('span', class_='companyCardWrapper__companyRatingCount').text.strip()
    reviews.append(company.find('span', class_='companyCardWrapper__ActionCount').text)
    c_type.append(company.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')[0])
    loc.append(company.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')[1])
    salary.append(company.find('span', class_='companyCardWrapper__ActionCount').text)
    rating[i] = rating[i]+" "+rat_count
    i += 1

In [146]:
d = {'comp_name':name, 'comp_rating':rating, 'comp_reviews':reviews, 'comp_type':c_type, 'location':loc, 'salaries':salary}

In [147]:
df = pd.DataFrame(d)

In [148]:
df

,comp_name,comp_rating,comp_reviews,comp_type,location,salaries
0,TCS,3.3 (1.1L),1.1L,IT Services & Consulting,Bengaluru +440 other locations,1.1L
1,Accenture,3.7 (72.9k),72.9k,IT Services & Consulting,Bengaluru +259 other locations,72.9k
2,Wipro,3.6 (64.7k),64.7k,IT Services & Consulting,Hyderabad +372 other locations,64.7k
3,Cognizant,3.7 (61k),61k,IT Services & Consulting,Hyderabad +234 other locations,61k
4,Capgemini,3.7 (52.7k),52.7k,IT Services & Consulting,Bengaluru +182 other locations,52.7k
5,HDFC Bank,3.8 (51.9k),51.9k,Banking,Mumbai +1843 other locations,51.9k
6,Infosys,3.5 (48.4k),48.4k,IT Services & Consulting,Bengaluru +248 other locations,48.4k
7,ICICI Bank,4.0 (45.6k),45.6k,Banking,Mumbai +1443 other locations,45.6k
8,HCLTech,3.4 (45.6k),45.6k,IT Services & Consulting,Chennai +234 other locations,45.6k
9,Tech Mahindra,3.4 (43.1k),43.1k,IT Services & Consulting,Hyderabad +331 other locations,43.1k
10,Genpact,3.6 (41.8k),41.8k,Analytics & KPO,Hyderabad +182 other locations,41.8k
11,TP,3.8 (37.9k),37.9k,BPO,Mumbai +257 other locations,37.9k
12,Jio,4.4 (33.6k),33.6k,Telecom,Mumbai +1963 other locations,33.6k
13,Axis Bank,3.6 (32.9k),32.9k,Banking,Mumbai +1516 other locations,32.9k
14,Concentrix Corporation,3.6 (32k),32k,BPO,Bengaluru +180 other locations,32k
15,Amazon,3.9 (31.4k),31.4k,Internet,Bengaluru +525 other locations,31.4k
16,Reliance Retail,3.9 (27.3k),27.3k,Retail,Mumbai +1159 other locations,27.3k
17,iEnergizer,4.6 (27.2k),27.2k,BPO,Noida +52 other locations,27.2k
18,LTIMindtree,3.6 (26.2k),26.2k,IT Services & Consulting,Bengaluru +145 other locations,26.2k
19,IBM,3.9 (25.7k),25.7k,IT Services & Consulting,Bengaluru +161 other locations,25.7k

In [111]:
type_loc[0].split('|')[0]

'IT Services & Consulting '

#### Working for multiple pages

In [166]:
company_dfs = pd.DataFrame() # Created a empty dataframe for the whole webpage

for i in range(0,100):
    url = f"https://www.ambitionbox.com/list-of-companies?page={i+1}"
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
    webpage = requests.get(url, headers=headers).text
    soup = BeautifulSoup(webpage, 'lxml')
    companies = soup.find_all('div', class_='companyCardWrapper')
    
    name = []
    rating = []
    reviews = []
    c_type = []
    loc = []
    salary = []
    i = 0

    for company in companies:
        name.append(company.find('h2').text.strip())
        rating.append(company.find('div', class_='rating_text').text.strip())
        rat_count = company.find('span', class_='companyCardWrapper__companyRatingCount').text.strip()
        reviews.append(company.find('span', class_='companyCardWrapper__ActionCount').text)
        c_type.append(company.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')[0])
        try:
            loc.append(company.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')[1])
        except:
            loc.append(pd.NA)
        salary.append(company.find('span', class_='companyCardWrapper__ActionCount').text)
        rating[i] = rating[i]+" "+rat_count
        i += 1

    d = {'comp_name':name, 'comp_rating':rating, 'comp_reviews':reviews, 'comp_type':c_type, 'location':loc, 'salaries':salary}
    df = pd.DataFrame(d)

    company_dfs = pd.concat([company_dfs, df], ignore_index=True)

In [167]:
company_dfs.shape

(2000, 6)

In [168]:
company_dfs.to_csv('companies.csv')