# K-NeighborsClassifier from scratch

## Define our own class for KNN

In [132]:
import numpy as np
from collections import Counter

class KNN:
    def __init__(self, n_neighbors=5):
        self.k = n_neighbors
        self.x_train = None
        self.y_train = None

    def fit(self, x_train, y_train):
        self.x_train = x_train
        self.y_train = y_train

    def predict(self, x_test):
        y_pred = []
        for i in x_test:
            distances = []
            for j in self.x_train:
                distances.append(self.calculate_distance(i, j))
            sorted_distances = sorted(list(enumerate(distances)), key = lambda x:x[1])
            n_neighbor = sorted_distances[0 : self.k]
            labels = self.majority_count(n_neighbor)
            y_pred.append(labels)
        return np.array(y_pred)

    def calculate_distance(self, pointA, pointB):
        return np.linalg.norm(pointA - pointB)

    def majority_count(self, neighbors):
        votes = []
        for i in neighbors:
            votes.append(y_train[i[0]])

        votes = Counter(votes)
        return votes.most_common()[0][0]

## Checking our KNN class

### Loading dataset

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("E:/Dataset/Social_Network_Ads.csv")

In [7]:
df = df.drop(columns=['User ID'])

In [9]:
df.sample(4)

    Gender  Age  EstimatedSalary  Purchased
349   Male   38            61000          0
5     Male   27            58000          0
37    Male   30            49000          0
359   Male   42            54000          0

In [10]:
df.shape

(400, 4)

### Encoding **Gender** column

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
encoder = LabelEncoder()

In [13]:
df['Gender'] = encoder.fit_transform(df['Gender'])

In [14]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

### Splitting and Scaling data

In [29]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [16]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=19)

In [77]:
from sklearn.preprocessing import StandardScaler

In [78]:
scaler = StandardScaler()

In [79]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

### Using own KNN class (model)

In [136]:
apnaKNN = KNN(n_neighbors=3)

In [137]:
apnaKNN.fit(x_train_scaled, y_train)

In [138]:
y_pred = apnaKNN.predict(x_test_scaled)

In [139]:
from sklearn.metrics import accuracy_score

In [140]:
accuracy_score(y_test, y_pred)

0.875

### Comparing with Scikit-Learn KNN class

In [141]:
from sklearn.neighbors import KNeighborsClassifier

In [142]:
knn_skl = KNeighborsClassifier(n_neighbors=3)

In [143]:
knn_skl.fit(x_train_scaled, y_train)
y_pred1 = knn_skl.predict(x_test_scaled)

In [144]:
accuracy_score(y_test, y_pred1)

0.875