# Column Transformer in Machine Learning

In [1]:
import numpy as np
import pandas as pd

In [22]:
df = pd.read_csv('E:\Dataset\covid_toy.csv')
df.sample(5)

    age  gender  fever   cough       city has_covid
81   65    Male   99.0    Mild      Delhi        No
7    20  Female    NaN  Strong     Mumbai       Yes
3    31  Female   98.0    Mild    Kolkata        No
35   82  Female  102.0  Strong  Bangalore        No
77    8  Female  101.0    Mild    Kolkata        No

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test, y_train,y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2, random_state=1)

In [8]:
x_train.shape, x_test.shape

((80, 5), (20, 5))

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

## Simple method of Transformation

In [18]:
# Adding imputer on fever column
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])  # Numpy array

x_test_fever = si.transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [31]:
# Adding OneHotEncoder on cough column
oe = OrdinalEncoder(categories=[['Mild','Strong']])

x_train_cough = oe.fit_transform(x_train[['cough']])  # Columns are in numerical form

x_test_cough = oe.fit_transform(x_test[['cough']])
x_train_cough.shape

(80, 1)

In [32]:
# Adding OneHotEncoder on gender, and city column
ohe = OneHotEncoder(sparse_output=False, drop='first')

x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])

x_test_gender_city = ohe.transform(x_test[['gender', 'city']])
x_train_gender_city.shape

(80, 4)

In [57]:
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values  # numpy array
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values
x_train_age.shape

(80, 1)

In [58]:
x_train_transformed = np.concatenate((x_train_age, x_train_gender_city, x_train_fever, x_train_cough), axis=1)
x_test_transformed = np.concatenate((x_test_age, x_test_gender_city, x_test_fever, x_test_cough),axis=1)
x_train_transformed.shape

(80, 7)

In [62]:
x_train_transformed = pd.DataFrame(x_train_transformed)
x_train_transformed.head()

      0    1    2    3    4           5    6
0  42.0  1.0  1.0  0.0  0.0  101.000000  0.0
1  34.0  1.0  0.0  1.0  0.0   98.000000  1.0
2  20.0  0.0  0.0  0.0  0.0  101.000000  0.0
3  56.0  0.0  0.0  0.0  0.0  104.000000  1.0
4  42.0  0.0  0.0  0.0  0.0  100.958333  1.0

## Transformation using Column Transformation

In [63]:
from sklearn.compose import ColumnTransformer