# Feature Splitting

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('E:/Dataset/titanic-dataset.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Extracting title of Name

In [17]:
df['Name'].str.split(',', expand=True).sample(3)

              0                                     1
591  Stephenson   Mrs. Walter Bertram (Martha Eustis)
196     Mernagh                            Mr. Robert
844   Culumovic                              Mr. Jeso

In [19]:
df['Name'].str.split(',', expand=True)[1].str.split('.', expand=True).sample(3)

         0                1     2
290   Miss   Ellen "Nellie"  None
749     Mr          Michael  None
218   Miss           Albina  None

In [21]:
df['title'] = df['Name'].str.split(',', expand=True)[1].str.split('.', expand=True)[0]

In [24]:
df[['title', 'Name']].head()

   title                                               Name
0     Mr                            Braund, Mr. Owen Harris
1    Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2   Miss                             Heikkinen, Miss. Laina
3    Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4     Mr                           Allen, Mr. William Henry

In [30]:
(df.groupby('title')['Survived'].mean()).sort_values(ascending=False)

title
the Countess    1.000000
Mlle            1.000000
Sir             1.000000
Ms              1.000000
Lady            1.000000
Mme             1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Col             0.500000
Major           0.500000
Dr              0.428571
Mr              0.156673
Jonkheer        0.000000
Rev             0.000000
Don             0.000000
Capt            0.000000
Name: Survived, dtype: float64