# Feature Construction

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Loading dataset

In [5]:
df = pd.read_csv('E:/Dataset/titanic-dataset.csv', usecols=['Survived','Pclass','Age','SibSp','Parch',])

In [7]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [8]:
df.shape

(891, 5)

In [11]:
df.dropna(inplace=True)

In [13]:
df.shape

(714, 5)

In [14]:
df.sample(2)

    Survived  Pclass   Age  SibSp  Parch
66         1       2  29.0      0      0
53         1       2  29.0      1      0

### Training data without feature construction

In [15]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [17]:
x.sample()

     Pclass   Age  SibSp  Parch
437       2  24.0      2      3

In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [20]:
cross_val_score(LogisticRegression(), x, y, scoring='accuracy', cv=20).mean()

np.float64(0.6933333333333332)

### Applying Feature Construction

In [21]:
x1 = x.copy()

In [22]:
x1.sample(2)

     Pclass   Age  SibSp  Parch
282       3  16.0      0      0
666       2  25.0      0      0

In [23]:
x1['family'] = x1['SibSp'] + x1['Parch'] + 1

In [24]:
x1.sample()

     Pclass   Age  SibSp  Parch  family
672       2  70.0      0      0       1

#### Function for defining family type

In [25]:
def family_size(num):
    if num==1:
        # Alone
        return 0
    elif num>1 and num<=4:
        # Small Family
        return 1
    else:
        # Large Family
        return 2

In [28]:
x1['family_type'] = x1['family'].apply(family_size)

In [33]:
x1.sample(2)

     Pclass   Age  SibSp  Parch  family  family_type
208       3  16.0      0      0       1            0
702       3  18.0      0      1       2            1

In [36]:
x1.drop(columns=['SibSp','Parch','family'], inplace=True)

In [37]:
x1.sample(2)

     Pclass   Age  family_type
529       2  23.0            1
216       3  27.0            0

In [39]:
cross_val_score(LogisticRegression(), x1, y, scoring='accuracy', cv=20).mean()

np.float64(0.7003174603174602)