# Imputation using Missing Indicator

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Loading dataset and splitting

In [4]:
df = pd.read_csv('E:/Dataset/titanic-Dataset.csv', usecols=['Age', 'Fare', 'Survived'])

In [6]:
df.sample(2)

     Survived   Age     Fare
693         0  25.0   7.2250
817         0  31.0  37.0042

In [7]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

### Calculating accuracy_score on imputing using SimpleImputer

In [12]:
from sklearn.impute import SimpleImputer

In [13]:
si = SimpleImputer()
x_train_trf = si.fit_transform(x_train)
x_test_trf = si.fit_transform(x_test)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
logReg = LogisticRegression()
logReg.fit(x_train_trf, y_train)
y_pred = logReg.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6145251396648045

### Calculating accuracy_score on imputation using Missing Indicator

In [17]:
from sklearn.impute import MissingIndicator

In [18]:
misInd = MissingIndicator()
x_train_miss = misInd.fit_transform(x_train)
x_test_miss = misInd.transform(x_test)

In [22]:
x_test_miss

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False]])

In [24]:
misInd.features_

array([0])

In [26]:
x_train['age_NaN'] = x_train_miss
x_test['age_NaN'] = x_test_miss

In [29]:
x_test.sample(4)

      Age     Fare  age_NaN
317  54.0  14.0000    False
304   NaN   8.0500     True
444   NaN   8.1125     True
15   55.0  16.0000    False

In [30]:
si = SimpleImputer()
x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [33]:
logReg.fit(x_train_trf2, y_train)
y_pred2 = logReg.predict(x_test_trf2)

accuracy_score(y_test, y_pred2)

0.6312849162011173

### Combination of MissingIndicator and SimpleImputer

In [34]:
simImp_misInd = SimpleImputer(add_indicator=True)

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [ ]:
x_train_trf3 =