# Handling-Date-Time

### Loading the dataset

In [1]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('E:/Dataset/orders.csv')
time = pd.read_csv('E:/Dataset/messages.csv')

In [4]:
date.head(3)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1

In [5]:
time.head(3)

                  date                                               msg
0  2013-12-15 00:50:00                          ищу на сегодня мужика 37
1  2014-04-29 23:40:00  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00          Днепр.м 43 позн.с д/ж *.о  067.16.34.576

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

### Working with Date

In [8]:
date['date'] = pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

#### Extract year

In [11]:
date['date_year'] = date['date'].dt.year

#### Extract month

In [13]:
date['date_month_no'] = date['date'].dt.month

In [14]:
date['date_month_name'] = date['date'].dt.month_name()

In [ ]:
date

In [15]:
date

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January
...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October
996,2018-12-06,5521,7,1,2018,12,December
997,2019-05-07,487,26,14,2019,5,May
998,2019-03-03,1503,21,2,2019,3,March
999,2019-10-15,6371,7,22,2019,10,October