# Classification metrics for **more than two classes**

### Loading data

In [1]:
import numpy as np
import pandas as pd

In [25]:
df = pd.read_csv('E:/Dataset/Iris.csv')

In [26]:
df.sample(3)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
35,36,5.0,3.2,1.2,0.2,Iris-setosa
81,82,5.5,2.4,3.7,1.0,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor

In [27]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [28]:
df1 = pd.read_csv('E:/Dataset/digit_recognition.csv')

In [29]:
df1.sample(2)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
40616,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30397,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
x1 = df1.iloc[:, 1:]
y1 = df1.iloc[:, 0]

### Encoding categorical data

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
encoder = LabelEncoder()

In [7]:
encoder.fit(y)

LabelEncoder()

In [8]:
encoder.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [9]:
y_encoded = encoder.transform(y)

In [10]:
y_encoded

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Splitting data

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=17)

In [35]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(x1, y1, test_size=0.2, random_state=17)

### Training model

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [14]:
log_reg = LogisticRegression()
dec_tree = DecisionTreeClassifier()

In [15]:
log_reg.fit(x_train, y_train)
dec_tree.fit(x_train, y_train)

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [17]:
y_pred1 = log_reg.predict(x_test)
y_pred2 = dec_tree.predict(x_test)

#### Model - 2

In [32]:
log_reg1 = LogisticRegression()
dec_tree1 = DecisionTreeClassifier()

In [36]:
log_reg1.fit(x_train1, y_train1)
dec_tree1.fit(x_train1, y_train1)

E:\Anaconda\Anaconda2\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [38]:
y_pred3 = log_reg1.predict(x_test1)
y_pred4 = dec_tree1.predict(x_test1)

### Testing Model

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [21]:
print(f"Accuracy(Logistic Regression): {accuracy_score(y_test, y_pred1)}")
print(f"Accuracy(Decision Tree): {accuracy_score(y_test, y_pred1)}")

Accuracy(Logistic Regression): 1.0
Accuracy(Decision Tree): 1.0

In [41]:
print(f"Confusion Matrics (Logistic Regression):\n {confusion_matrix(y_test, y_pred1)}")
print(f"\nConfusion Matrix(Decision Tree):\n {confusion_matrix(y_test, y_pred1)}")

Confusion Matrics (Logistic Regression):
 [[ 7  0  0]
 [ 0 11  0]
 [ 0  0 12]]

Confusion Matrix(Decision Tree):
 [[ 7  0  0]
 [ 0 11  0]
 [ 0  0 12]]

#### Model - 2

In [39]:
print(f"Accuracy(Logistic Regression): {accuracy_score(y_test1, y_pred3)}")
print(f"Accuracy(Decision Tree): {accuracy_score(y_test1, y_pred4)}")

Accuracy(Logistic Regression): 0.9161904761904762
Accuracy(Decision Tree): 0.8479761904761904

In [42]:
print(f"Confusion Matrics (Logistic Regression):\n {confusion_matrix(y_test1, y_pred3)}")
print(f"\nConfusion Matrix(Decision Tree):\n {confusion_matrix(y_test1, y_pred4)}")

Confusion Matrics (Logistic Regression):
 [[831   0   4   3   2   6   7   3   4   2]
 [  0 891   5   3   1   5   1   1  11   3]
 [  6  11 759  19   6   3  13  16  22   3]
 [  5   2  18 789   0  32   2  11  15   9]
 [  2   3   4   3 708   2   9   2   6  22]
 [ 13   1   4  31   9 647   6   2  24  11]
 [  4   3   7   0   8  14 750   0   4   1]
 [  2   2   9   6   4   2   2 849   6  31]
 [  3  16  10  24   4  21   8   4 721  17]
 [  1   3   2  14  21   9   0  28   6 751]]

Confusion Matrix(Decision Tree):
 [[794   2   8  10   6   9   9   4  12   8]
 [  0 853  11  18   5  12   4   0  11   7]
 [ 10  12 696  27  20   7  19  27  25  15]
 [ 11   9  29 718   6  30   6  15  32  27]
 [  3   8   7   3 646   9  22  11  15  37]
 [  6  14   7  51   9 581  22   8  30  20]
 [  9   8  10   7  16  27 698   1   7   8]
 [  7   5  22  11   9   6   0 814   9  30]
 [ 13  14  28  39  22  28  19   7 631  27]
 [ 10   3   5  31  32  14   2  33  13 692]]