# Simple example of DT Classifier

### Loading dataset

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('E:/Dataset/Social_Network_Ads.csv')

In [11]:
data.head(5)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [65]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

### splitting and encoding data

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x = data.iloc[:, 1:-1]
y = data.iloc[:, -1]

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=20)

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
encoder = OrdinalEncoder(categories=[['Male', 'Female']])

In [21]:
x_train['Gender'] = encoder.fit_transform(x_train[['Gender']])
x_test['Gender'] = encoder.transform(x_test[['Gender']])

In [25]:
encoder.categories_

[array(['Male', 'Female'], dtype=object)]

In [26]:
x_train.head()

     Gender  Age  EstimatedSalary
94      1.0   29            83000
91      1.0   30           116000
89      0.0   35            50000
329     1.0   47           107000
129     1.0   26            84000

### Model training and finding accuracy

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

#### Training model on different criterion

In [41]:
dt_clasifier = DecisionTreeClassifier(criterion='gini')
dt_clasifier.fit(x_train, y_train)
y_pred = dt_clasifier.predict(x_test)
accuracy_score(y_test, y_pred)

0.825

In [42]:
dt_clasifier1 = DecisionTreeClassifier(criterion='entropy')
dt_clasifier1.fit(x_train, y_train)
y_pred = dt_clasifier1.predict(x_test)
accuracy_score(y_test, y_pred)

0.85

In [55]:
dt_clasifier = DecisionTreeClassifier(criterion='log_loss')
dt_clasifier.fit(x_train, y_train)
y_pred = dt_clasifier.predict(x_test)
accuracy_score(y_test, y_pred)

0.85

#### Adding max_depth hyperparameter

In [52]:
dt_clasifier = DecisionTreeClassifier(criterion='gini', max_depth=2)
dt_clasifier.fit(x_train, y_train)
y_pred = dt_clasifier.predict(x_test)
accuracy_score(y_test, y_pred)

0.9125

In [53]:
dt_clasifier = DecisionTreeClassifier(criterion='entropy', max_depth=2)
dt_clasifier.fit(x_train, y_train)
y_pred = dt_clasifier.predict(x_test)
accuracy_score(y_test, y_pred)

0.9125

In [59]:
dt_clasifier = DecisionTreeClassifier(criterion='log_loss', max_depth=2)
dt_clasifier.fit(x_train, y_train)
y_pred = dt_clasifier.predict(x_test)
accuracy_score(y_test, y_pred)

0.9125

## - Final conclusion is that on this dataset -
#### i) it does not depends on any criterion, it depends only on max_depth
#### ii) max_depth=2 is the best decision making boundary.